### ISSUE TITLE
Error with Testing the code 

### ISSUE THREAD

**Issue by Harshitasahni** [learningmatter-mit/GenZProt#3]
Starting testing
Traceback (most recent call last):
  File "test_model.py", line 384, in <module>
    run_cv(params)
  File "test_model.py", line 223, in run_cv
    get_all_true_reconstructed_structures(testloader,
  File "/users/hsahni/data_genz/GenZProt/scripts/utils.py", line 405, in get_all_true_reconstructed_structures
    true_xyzs = torch.cat(true_xyzs).numpy()
RuntimeError: torch.cat(): expected a non-empty list of Tensors

**Comment by SoojungYang** [comment]
Hi Harshitasahni, thank you for your interest in using our code. Could you provide us with your input files (both all atom topology file (${top_path}) and coarse-grained pdb file ($ca_trace_path)) so that we can look into the issue?
